csv.cpp, encoding_converter.cpp, tests/multi_obj_pool_test.cpp, timer.cpp
=> All: remove clang warning

functions.h, tests/utils_test.cpp
This function finds if value is in the container.
the original version of this code:
http://codereview.stackexchange.com/questions/59997/contains-algorithm-for-stdvector
the trick of `decltype` + comma operator for SFINAE:
http://stackoverflow.com/questions/18265536/sfinae-decltype-comma-operator-trick
=> Add function contains

serialization_flat_map.h, serialization_unordered_set.h
Also light refactor of unordered_map(reserve_imp + variadic template)
=> Add serialization for flat_map and unordered_set

obj_factory.h, tests/CMakeLists.txt, tests/obj_factory_test.cpp
=> Add ObjFactory for creation and management of collections

multi_obj_pool.h, tests/multi_obj_pool_test.cpp
adds visitor (for tracing) and is_dominated method
=> adding pareto features

serialization_unique_ptr_container.h
it was working only for vector
=> add map of unique_ptr serialization

obj_factory.h
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canaltp/utils/33)
=> specialize find_or_default for obj factory

flat_enum_map.h
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canaltp/utils/34)
=> add a at method to flat map

lru.h, tests/lru_test.cpp
impossible to make lru with no cache
=> secure lru

paginate.h
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canaltp/utils/38)
=> paginate can be a bit more generic

CMakeLists.txt, zmq.cpp, zmq.h
it implements: http://zguide.zeromq.org/php:chapter3#header-73
it's a first version, some tests seem to fail in jormungandr since this change, investigation is under way
=> add a load balancer for zmq

lotus.cpp
Ticket concerned: http://jira.canaltp.fr/browse/NAVITIAII-2130
=> utils: modification to allow NULL as text value

tests/CMakeLists.txt
=> upgrade boost version to match navitia one

CMakeLists.txt, alphanum.hpp, coord_parser.cpp, coord_parser.h, functions.cpp, tests/utils_test.cpp
Improve `navitia::pseudo_natural_sort` using http://www.davekoelle.com/files/alphanum.hpp
Cleanups coord_parser at the same time
=> Natural sort

README.md, coord_parser.h
It's not useful as default is defined
=> Debian7 compile: no using constructor

csv.cpp, csv.h
=> utils/Csv : Carriage return in CSV

pairs_generator.h, tests/CMakeLists.txt, tests/pairs_generator_test.cpp
Implementation of Pair Generator that we use for filtering night bus.
=> Pairs generator for min nb journeys

pairs_generator.h
=> Fix gcc 4.8

tests/idx_map_test.cpp, tests/map_find_test.cpp, tests/utils_test.cpp
=> Remove clang warning

map_find.h, obj_factory.h
Just for the sake of consistency between use of idx and uri
=> Add exists(idx)

functions.h
PR to optimise to sort vj list from index of an objet deleted instead of index 0
Related to https://jira.kisio.org/browse/NAVITIAII-2694
=> utils: Sort from Index of object if passed in parameter

rank.h
To be used for StopTime, JourneyPatternPoint
Got most inspiration from Idx, added operators and serialize
Work initiated after https://github.com/CanalTP/navitia/pull/2959
TODO (`do_not_merge`):
=> Add rank type to allow strong-typing of order

zmq.cpp
our CI doesn't have "size() const" :(
=> use non const message_t because of CI

timer.cpp, timer.h
How to use it :
```cpp
auto log = log4cplus::getLogger("Log");
{
TimerGuard t([&](const StopWatch& sw){ 
LOG4CPLUS_INFO(log, "Time elapsed to performe the loop : " << sw.elapsed() << " us")
});
for_earch(my_container, do_work);
}
```
=> Add little utility tool to time things with a stop watch

idx_map.h
Add helper functions to construct or resize and IdxMap based on a size.
=> Add Constructor and resize function to IdxMap

lru.h
=> Revert "add lru log"

lru.h
Use std::mutex instead of boost::mutex
A compile error occurs under debian-8 when using boost::mutex
=> Fix LRU Cache for Debian 8

paginate.h
Jira: [NAVP-1896](https://jira.kisio.org/browse/NAVP-1896)
Paginate for /vehicle_positions end_point
=> paginate function adapted for std:map type

zmq.cpp, zmq.h
so that kraken can be behind several layers of ROUTER sockets
=> [ZMQ] allow more than one frame to identify the client
